#!/usr/bin/python3
import sys
from math import sqrt, gcd, ceil


arg1 = str(sys.argv[1])

File = open(arg1, 'r')

lines = File.readlines()

for line in lines:
    
    N = int(line)
    M = 1
    sqrtN = ceil(sqrt(N))

    while sqrtN < N: 
        a = sqrtN * sqrtN
        a -= 1
        cd = gcd(a, N)
        if cd > 1:
            M = cd
            break
        sqrtN += 1


    print("{:d}={:d}*{:d}".format(N, N//M, M))
